In [23]:
import pandas as pd
import json

In [27]:
!wget https://raw.githubusercontent.com/audioset/ontology/master/ontology.json

--2021-12-07 20:49:39--  https://raw.githubusercontent.com/audioset/ontology/master/ontology.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 342780 (335K) [text/plain]
Saving to: ‘ontology.json’

ontology.json       100%[===================>] 334.75K   923KB/s    in 0.4s

2021-12-07 20:49:40 (923 KB/s) - ‘ontology.json’ saved [342780/342780]

In [30]:
with open('ontology.json') as json_file:
    ontology = json.load(json_file)
ontology = {x['id']: x for x in ontology}

In [10]:
csv_path = 'balanced_train_segments.csv'
pd.read_csv(csv_path, delimiter=', ', header=2)

/home/teo/.local/lib/python3.8/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

,# YTID,start_seconds,end_seconds,positive_labels
0,--PJHxphWEs,30.0,40.0,"""/m/09x0r,/t/dd00088"""
1,--ZhevVpy1s,50.0,60.0,"""/m/012xff"""
2,--aE2O5G5WE,0.0,10.0,"""/m/03fwl,/m/04rlf,/m/09x0r"""
3,--aO5cdqSAg,30.0,40.0,"""/t/dd00003,/t/dd00005"""
4,--aaILOrkII,200.0,210.0,"""/m/032s66,/m/073cg4"""
...,...,...,...,...
22155,zyqg4pYEioQ,20.0,30.0,"""/m/09x0r,/m/0llzx"""
22156,zz0ddNfz0h0,30.0,40.0,"""/m/012f08,/m/03cl9h,/m/07yv9,/m/0k4j"""
22157,zz8TGV83nkE,80.0,90.0,"""/m/012f08,/m/02mk9,/m/04_sv,/m/07yv9"""
22158,zzlK8KDqlr0,370.0,380.0,"""/m/01m2v,/m/07qc9xj,/m/09x0r,/t/dd00125"""
22159,zzya4dDVRLk,30.0,40.0,"""/m/01v_m0,/m/0hdsk"""

In [31]:
class AudioSet:
  def __init__(self, wav_dir, csv_path, ontology_json_path):
    self.dir = wav_dir
    
    self.meta = pd.read_csv(csv_path, delimiter=', ', header=2)
    self.ontology = load_ontology(ontology_json_path)
    
  def filter_by_existence(self):
    return
  
  def __len__(self):
    return len(self.meta)
      
  def __getitem__(self, idx):
    return

def load_ontology(json_path):
  with open('ontology.json') as json_file:
    ontology = json.load(json_file)
  ontology = {x['id']: x for x in ontology}
  return ontology

def get_audio_id_list(dir_path):
  wav_files = dir_path.glob('*.wav')
  ids = [x.split]
  return 
  
  
dataset = AudioSet('AudioSet/', 'balanced_train_segments.csv', 'ontology.json')

TypeError: __init__() missing 1 required positional argument: 'ontology_json_path'

In [13]:
dataset.meta

,# YTID,start_seconds,end_seconds,positive_labels
0,--PJHxphWEs,30.0,40.0,"""/m/09x0r,/t/dd00088"""
1,--ZhevVpy1s,50.0,60.0,"""/m/012xff"""
2,--aE2O5G5WE,0.0,10.0,"""/m/03fwl,/m/04rlf,/m/09x0r"""
3,--aO5cdqSAg,30.0,40.0,"""/t/dd00003,/t/dd00005"""
4,--aaILOrkII,200.0,210.0,"""/m/032s66,/m/073cg4"""
...,...,...,...,...
22155,zyqg4pYEioQ,20.0,30.0,"""/m/09x0r,/m/0llzx"""
22156,zz0ddNfz0h0,30.0,40.0,"""/m/012f08,/m/03cl9h,/m/07yv9,/m/0k4j"""
22157,zz8TGV83nkE,80.0,90.0,"""/m/012f08,/m/02mk9,/m/04_sv,/m/07yv9"""
22158,zzlK8KDqlr0,370.0,380.0,"""/m/01m2v,/m/07qc9xj,/m/09x0r,/t/dd00125"""
22159,zzya4dDVRLk,30.0,40.0,"""/m/01v_m0,/m/0hdsk"""

--2021-12-07 20:42:42--  https://github.com/audioset/ontology/blob/master/ontology.json
Resolving github.com (github.com)... 15.164.81.167
Connecting to github.com (github.com)|15.164.81.167|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘ontology.json’

ontology.json           [      <=>           ]   2.37M  2.12MB/s    in 1.1s

2021-12-07 20:42:43 (2.12 MB/s) - ‘ontology.json’ saved [2485899]